In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import math
import tensorflow as tf
%matplotlib inline

df = pd.read_csv('FullData.csv')

In [2]:
df.head()

Name Nationality National_Position  National_Kit  \
0  Cristiano Ronaldo    Portugal                LS           7.0   
1       Lionel Messi   Argentina                RW          10.0   
2             Neymar      Brazil                LW          10.0   
3        Luis Suárez     Uruguay                LS           9.0   
4       Manuel Neuer     Germany                GK           1.0   

           Club Club_Position  Club_Kit Club_Joining  Contract_Expiry  Rating  \
0   Real Madrid            LW       7.0   07/01/2009           2021.0      94   
1  FC Barcelona            RW      10.0   07/01/2004           2018.0      93   
2  FC Barcelona            LW      11.0   07/01/2013           2021.0      92   
3  FC Barcelona            ST       9.0   07/11/2014           2021.0      92   
4     FC Bayern            GK       1.0   07/01/2011           2021.0      92   

      ...      Long_Shots Curve Freekick_Accuracy Penalties  Volleys  \
0     ...              90    81                76        85       88   
1     ...              88    89                90        74       85   
2     ...              77    79                84        81       83   
3     ...              86    86                84        85       88   
4     ...              16    14                11        47       11   

  GK_Positioning GK_Diving  GK_Kicking  GK_Handling  GK_Reflexes  
0             14         7          15           11           11  
1             14         6          15           11            8  
2             15         9          15            9           11  
3             33        27          31           25           37  
4             91        89          95           90           89  

[5 rows x 53 columns]

# Let's remove some stuff in here

In [3]:
df.shape

(17588, 53)

In [4]:
df.columns.tolist()

['Name',
 'Nationality',
 'National_Position',
 'National_Kit',
 'Club',
 'Club_Position',
 'Club_Kit',
 'Club_Joining',
 'Contract_Expiry',
 'Rating',
 'Height',
 'Weight',
 'Preffered_Foot',
 'Birth_Date',
 'Age',
 'Preffered_Position',
 'Work_Rate',
 'Weak_foot',
 'Skill_Moves',
 'Ball_Control',
 'Dribbling',
 'Marking',
 'Sliding_Tackle',
 'Standing_Tackle',
 'Aggression',
 'Reactions',
 'Attacking_Position',
 'Interceptions',
 'Vision',
 'Composure',
 'Crossing',
 'Short_Pass',
 'Long_Pass',
 'Acceleration',
 'Speed',
 'Stamina',
 'Strength',
 'Balance',
 'Agility',
 'Jumping',
 'Heading',
 'Shot_Power',
 'Finishing',
 'Long_Shots',
 'Curve',
 'Freekick_Accuracy',
 'Penalties',
 'Volleys',
 'GK_Positioning',
 'GK_Diving',
 'GK_Kicking',
 'GK_Handling',
 'GK_Reflexes']

In [5]:
df.isnull().sum()

Name                      0
Nationality               0
National_Position     16513
National_Kit          16513
Club                      0
Club_Position             1
Club_Kit                  1
Club_Joining              1
Contract_Expiry           1
Rating                    0
Height                    0
Weight                    0
Preffered_Foot            0
Birth_Date                0
Age                       0
Preffered_Position        0
Work_Rate                 0
Weak_foot                 0
Skill_Moves               0
Ball_Control              0
Dribbling                 0
Marking                   0
Sliding_Tackle            0
Standing_Tackle           0
Aggression                0
Reactions                 0
Attacking_Position        0
Interceptions             0
Vision                    0
Composure                 0
Crossing                  0
Short_Pass                0
Long_Pass                 0
Acceleration              0
Speed                     0
Stamina             

# Looks like National_position and National_kit are very NaN. Let's drop them.

In [6]:
df.drop(['National_Position','National_Kit','Contract_Expiry','Name','Club','Birth_Date','Weight','Height'], axis=1, inplace=True)
df = df.dropna()

In [7]:
df.isnull().sum()

Nationality           0
Club_Position         0
Club_Kit              0
Club_Joining          0
Rating                0
Preffered_Foot        0
Age                   0
Preffered_Position    0
Work_Rate             0
Weak_foot             0
Skill_Moves           0
Ball_Control          0
Dribbling             0
Marking               0
Sliding_Tackle        0
Standing_Tackle       0
Aggression            0
Reactions             0
Attacking_Position    0
Interceptions         0
Vision                0
Composure             0
Crossing              0
Short_Pass            0
Long_Pass             0
Acceleration          0
Speed                 0
Stamina               0
Strength              0
Balance               0
Agility               0
Jumping               0
Heading               0
Shot_Power            0
Finishing             0
Long_Shots            0
Curve                 0
Freekick_Accuracy     0
Penalties             0
Volleys               0
GK_Positioning        0
GK_Diving       

In [8]:
df.shape

(17587, 45)

In [9]:
df.iloc[0]

Nationality             Portugal
Club_Position                 LW
Club_Kit                       7
Club_Joining          07/01/2009
Rating                        94
Preffered_Foot             Right
Age                           32
Preffered_Position         LW/ST
Work_Rate             High / Low
Weak_foot                      4
Skill_Moves                    5
Ball_Control                  93
Dribbling                     92
Marking                       22
Sliding_Tackle                23
Standing_Tackle               31
Aggression                    63
Reactions                     96
Attacking_Position            94
Interceptions                 29
Vision                        85
Composure                     86
Crossing                      84
Short_Pass                    83
Long_Pass                     77
Acceleration                  91
Speed                         92
Stamina                       92
Strength                      80
Balance                       63
Agility   

In [10]:
df[df.select_dtypes(exclude=[np.number]).columns] = df.select_dtypes(exclude=[np.number]).apply(lambda x: pd.factorize(x)[0])

In [11]:
# Check afterwards
df.iloc[0]

Nationality            0.0
Club_Position          0.0
Club_Kit               7.0
Club_Joining           0.0
Rating                94.0
Preffered_Foot         0.0
Age                   32.0
Preffered_Position     0.0
Work_Rate              0.0
Weak_foot              4.0
Skill_Moves            5.0
Ball_Control          93.0
Dribbling             92.0
Marking               22.0
Sliding_Tackle        23.0
Standing_Tackle       31.0
Aggression            63.0
Reactions             96.0
Attacking_Position    94.0
Interceptions         29.0
Vision                85.0
Composure             86.0
Crossing              84.0
Short_Pass            83.0
Long_Pass             77.0
Acceleration          91.0
Speed                 92.0
Stamina               92.0
Strength              80.0
Balance               63.0
Agility               90.0
Jumping               95.0
Heading               85.0
Shot_Power            92.0
Finishing             93.0
Long_Shots            90.0
Curve                 81.0
F

In [12]:
mat = df.values
mat.shape
type(mat)

numpy.ndarray

# Let's do some biconvex matrix completion yay

In [13]:
y = mat
# Turn random index of every matrix into NaN.
m,n = y.shape
num_to_remove = 100 # 20000 values(roughly)
keep = np.ones((m,n))
to_remove = np.array([np.random.randint(m,size=(num_to_remove,)), np.random.randint(n,size=(num_to_remove,))]).T
print(to_remove[0,:20])
keep[to_remove[:,0], to_remove[:,1]] = 0
to_remove.shape
keep

[11704    32]


array([[ 1.,  1.,  1., ...,  1.,  1.,  1.],
       [ 1.,  1.,  1., ...,  1.,  1.,  1.],
       [ 1.,  1.,  1., ...,  1.,  1.,  1.],
       ..., 
       [ 1.,  1.,  1., ...,  1.,  1.,  1.],
       [ 1.,  1.,  1., ...,  1.,  1.,  1.],
       [ 1.,  1.,  1., ...,  1.,  1.,  1.]])

In [14]:
x = y.copy()
x

array([[  0.,   0.,   7., ...,  15.,  11.,  11.],
       [  1.,   1.,  10., ...,  15.,  11.,   8.],
       [  2.,   0.,  11., ...,  15.,   9.,  11.],
       ..., 
       [ 21.,  21.,  32., ...,  13.,  14.,   7.],
       [ 69.,   4.,  45., ...,  44.,  43.,  45.],
       [ 21.,   4.,  13., ...,  37.,  51.,  33.]])

# So we pretty much want to start with some assumptions:
Our data lies within a lower dimension. I.e. the matrix is sparse.
$X = LR^T$, where $X \in \mathbb{R}^{mxn}$, and $L \in \mathbb{R}^{mxp}$, $R \in \mathbb{R}^{nxp}$. 

Using the spectral decomposition, one can see that $L = U\Sigma^{1/2}$ and $R = V\Sigma^{1/2}$.

By definition, $rank(X) \leq p$ if p is small.

The optimization objective is:

$min_{L,R} ||L||^2_F + ||R||^2_F$

s.t. $LR^T = X$.

However, the above is not a convex formulation. We don't want NP-hardness in our butt:

$min_{L,R} \sum_{(i,j) \in \Omega} ((LR^T)_{i,j} - X_{i,j})^2 + \lambda(||L||^2_F + ||R||^2_F)$ unconstrained, imposing an implicit proximal operator of $prox_{\lambda L}$ where L is the MSE.

In [15]:
p = 20 # Assume our data lies within rank 30 singular matrix.
learning_rate = 1e-3
train_iter = 10000

L = tf.Variable(tf.truncated_normal([m,p]), name="players")
R = tf.Variable(tf.truncated_normal([n,p]), name="features")
X = tf.placeholder(tf.float32, shape=[m,n])
Keep = tf.placeholder(tf.float32, shape=[m,n])
Lambda = tf.placeholder(tf.float32)

In [16]:
predict = tf.matmul(L,tf.transpose(R))
result = tf.reduce_sum((tf.square(predict- X)) * Keep)
loss = result + Lambda*(tf.norm(L) + tf.norm(R))
train_op = tf.train.AdamOptimizer(learning_rate).minimize(loss)

init_op = tf.global_variables_initializer()

with tf.Session() as sess:
    sess.run(init_op)
    for i in range(train_iter):
        _,val = sess.run([train_op, loss], feed_dict={X : x, Keep : keep, Lambda : 1.0})
        if i % 100 == 0:
            print(val)
    
    # Prediction:
    ans = sess.run(predict)

6.66267e+09
6.61063e+09
6.49309e+09
6.30619e+09
6.06693e+09
5.79632e+09
5.51477e+09
5.23935e+09
4.98255e+09
4.7525e+09
4.55309e+09
4.38408e+09
4.24208e+09
4.12179e+09
4.01738e+09
3.92359e+09
3.83621e+09
3.75215e+09
3.66927e+09
3.58611e+09
3.50171e+09
3.41551e+09
3.32724e+09
3.23688e+09
3.14466e+09
3.05095e+09
2.95625e+09
2.86113e+09
2.76616e+09
2.6719e+09
2.57881e+09
2.48724e+09
2.39742e+09
2.30939e+09
2.22303e+09
2.13802e+09
2.05384e+09
1.96986e+09
1.88533e+09
1.79954e+09
1.71198e+09
1.62251e+09
1.53151e+09
1.43977e+09
1.34843e+09
1.25868e+09
1.17163e+09
1.08812e+09
1.00874e+09
9.33811e+08
8.63473e+08
7.97713e+08
7.36425e+08
6.79439e+08
6.26545e+08
5.77519e+08
5.32123e+08
4.90123e+08
4.51286e+08
4.15386e+08
3.82207e+08
3.5155e+08
3.23225e+08
2.97058e+08
2.72892e+08
2.5058e+08
2.29992e+08
2.11004e+08
1.93507e+08
1.77397e+08
1.62579e+08
1.48963e+08
1.36467e+08
1.25013e+08
1.14528e+08
1.04943e+08
9.61959e+07
8.82267e+07
8.09805e+07
7.4405e+07
6.84509e+07
6.30713e+07
5.82211e+07
5.38565e+

In [17]:
# Look at the not-computed values:
quick_look = np.array([ans[~keep.astype(np.bool)], x[~keep.astype(np.bool)]]).T
np.set_printoptions(threshold=np.inf) # Just print the entire thing unless you set the missing values too high:
print(quick_look)

[[  7.63087692e+01   8.00000000e+01]
 [  7.37039185e+01   7.40000000e+01]
 [  8.14593201e+01   7.30000000e+01]
 [  8.13432083e+01   9.00000000e+01]
 [  6.87206497e+01   7.80000000e+01]
 [  1.10836821e+01   4.00000000e+00]
 [  1.11151228e+01   1.60000000e+01]
 [  6.54067307e+01   6.90000000e+01]
 [  5.15516663e+01   5.90000000e+01]
 [ -6.98774815e+00   4.00000000e+00]
 [  6.97809525e+01   7.60000000e+01]
 [  5.53108521e+01   5.40000000e+01]
 [  3.90206482e+02   6.91000000e+02]
 [  5.76114868e+02   4.22000000e+02]
 [  2.84120655e+00   3.00000000e+00]
 [  3.60661209e-01   0.00000000e+00]
 [  5.00786476e+01   6.70000000e+01]
 [  7.83588257e+01   9.00000000e+01]
 [  2.91611624e+00   2.00000000e+00]
 [  2.63210754e+01   3.00000000e+01]
 [  6.43506088e+01   6.60000000e+01]
 [  6.67092743e+01   7.60000000e+01]
 [  2.06210375e+00   2.00000000e+00]
 [  1.17174644e+01   1.40000000e+01]
 [  5.05693436e+01   2.30000000e+01]
 [  2.22066784e+01   7.00000000e+00]
 [  4.98724518e+01   5.10000000e+01]
 